### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by juancarlospaco** [jyapayne/mort#1]
So I shared the project with some friends/coworkers, here is some feedback,
is not very clear what this project does for a new user because Nim already has Dead Code Elimination built-in,
so maybe you can add a tiny section on the readme
**explaining whats the difference between this and Nims Dead Code Elimination.**

Awesome work, keep it up. :+1:

**Comment by jyapayne** [comment]
Ah, interesting. Thank you for the feedback! Yes, Nim has dead code elimination, but it doesn't remove dead branches, only function calls. I will try to specify that in the README.

**Comment by jyapayne** [comment]
I've updated the README. If you could share it again with your friends/coworkers and get more feedback on the clarity, that would be amazing :)
